In [2]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import altair as alt

In [ ]:
path = './data/measles_incidence.csv' # this is a relative path 
data = pd.read_csv(path, skiprows=2, na_values='-')
data.head()

In [3]:
# Print out the current working directory
%pwd

'C:\\Users\\Tristan\\Documents'

In [128]:
path = 'C:/Users/Tristan/Desktop/ForestTransition/vaccinegrid/PS_2001_2006_t_r.csv' # this is a relative path 
data = pd.read_csv(path, skiprows=0, na_values='-')
data.head()

,YEAR,Austria,Belgium,Bosnia and Herzegovina,Croatia,Czechia,Estonia,Finland,France,Germany,Hungary,Latvia,Lithuania,Luxembourg,Poland,Romania,Serbia,Slovakia,Slovenia,Sweden
0,1985,66.688454,69.428574,69.792946,74.933525,70.703476,67.157890,56.606483,64.249283,64.643219,67.639610,67.042664,70.926666,73.674744,62.238148,66.631516,70.057266,65.455635,74.555862,61.610291
1,1987,66.360794,70.778252,67.485504,76.769180,69.624725,64.534042,58.046352,67.075226,64.636520,67.306900,66.181725,71.145042,75.496750,64.038155,64.776276,68.998947,75.215889,76.389633,62.232418
2,1989,66.776276,67.015450,66.262085,77.194267,67.344193,66.971298,54.947178,64.204239,62.976475,67.016899,66.674263,70.318466,72.222542,63.005661,65.966766,69.615608,73.361191,77.085289,60.471600
3,1991,64.557541,63.313442,68.908302,74.719292,68.233383,61.863609,53.751945,64.313026,61.278599,68.500435,65.319649,67.268829,69.664528,57.341579,62.972771,70.178909,71.297241,74.961029,56.215763
4,1993,66.065125,68.772255,68.829300,75.754578,70.636169,67.234276,56.692204,67.547104,66.291016,67.138687,66.453911,69.063828,71.386246,62.899353,68.912422,70.457138,74.227806,76.651337,60.647064

In [129]:
datalong = data.melt(id_vars='YEAR', value_name="NDVI", var_name="country")
datalong.head(n=40)

    YEAR                 country       NDVI
0   1985                 Austria  66.688454
1   1987                 Austria  66.360794
2   1989                 Austria  66.776276
3   1991                 Austria  64.557541
4   1993                 Austria  66.065125
5   1995                 Austria  67.826118
6   1997                 Austria  68.606934
7   1999                 Austria  70.464897
8   2001                 Austria  70.908623
9   2003                 Austria  66.643631
10  2005                 Austria  68.199577
11  2007                 Austria  66.943520
12  2009                 Austria  67.773788
13  2011                 Austria  67.161423
14  2013                 Austria  72.599007
15  2015                 Austria  74.200310
16  2017                 Austria  74.045105
17  2019                 Austria  74.207001
18  1985                 Belgium  69.428574
19  1987                 Belgium  70.778252
20  1989                 Belgium  67.015450
21  1991                 Belgium  63.313442
22  1993                 Belgium  68.772255
23  1995                 Belgium  70.993156
24  1997                 Belgium  70.217133
25  1999                 Belgium  75.893600
26  2001                 Belgium  76.648560
27  2003                 Belgium  70.966698
28  2005                 Belgium  72.449165
29  2007                 Belgium  71.229294
30  2009                 Belgium  72.922737
31  2011                 Belgium  69.404854
32  2013                 Belgium  79.788826
33  2015                 Belgium  78.791695
34  2017                 Belgium  75.266785
35  2019                 Belgium  77.117752
36  1985  Bosnia and Herzegovina  69.792946
37  1987  Bosnia and Herzegovina  67.485504
38  1989  Bosnia and Herzegovina  66.262085
39  1991  Bosnia and Herzegovina  68.908302

In [130]:
colormap = alt.Scale(
    domain=[55, 65, 75, 85],
    range=[
        "white",
        "mediumseagreen",
    ],
    type="sqrt",
)

In [131]:
alt.data_transformers.enable('json')

DataTransformerRegistry.enable('json')

In [138]:
threshold = pd.DataFrame([{"threshold": 2003}])
threshold
# Vertical line for vaccination year
rule = alt.Chart(threshold).mark_rule(strokeWidth=4).encode(x="threshold:O")


chart = (
   alt.Chart(datalong)
    .mark_rect()
   .encode(
       x=alt.X("YEAR:O", axis=alt.Axis(title=None, ticks=False)),
       y=alt.Y("country:N", axis=alt.Axis(title=None, ticks=False)),
       color=alt.Color("NDVI:Q", sort="ascending", scale=colormap),
       tooltip=["country", "YEAR", "NDVI"],
   )
   .properties(width=500, height=500)
)

chart #+ rule

alt.Chart(...)